Repository server-state/client-base, pull requests merged in 2019-11, with the labels that each got.

#8 Ensuring being compliant with the specs
  package.json
  src/App.js
  src/App.test.js
  src/components/content-element-wrapper.js
  src/components/dashboard.js
  src/components/front-end-modules/systemd/systemd-badge.js
  src/components/front-end-modules/systemd/systemd-dialog-title.js
  src/components/front-end-modules/systemd/systemd-dialog.js
  src/components/front-end-modules/systemd/systemd-icon-generator.js
  src/components/front-end-modules/systemd/systemd-icon-suggestions.md
  src/components/front-end-modules/systemd/systemd-list-item.js
  src/components/front-end-modules/systemd/systemd-mapper.js
  src/components/front-end-modules/systemd/systemd-table.js
  src/components/front-end-modules/systemd/systemd.js
  src/config/component-registry.js
  yarn.lock
Labels: dependencies, enhancement

#9 Added cypress for intregation/e2e testing
  .gitignore
  .travis.yml
  cypress.json
  cypress/integration/test_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  src/components/dashboard.js
  src/components/front-end-modules/linux-raid.js
  yarn.lock
Labels: enhancement

#15 Bumped dependencies
  package.json
  yarn.lock
Labels: dependencies
